monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.platform-sound.*"
      }
    ]
    actions = {
      update-props = {
        api.alsa.disable-mmap = true
        audio.format = "S16LE"
      }
    }
  }
]
