SectionVerb {
	EnableSequence [
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		cset "name='SEC_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Headphones" {
	Comment "AK4376 Headphones"

	ConflictingDevice [
		"Speaker"
	]

	EnableSequence [
		cset "name='SEC_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='HPL Mixer LDACL Switch' 1"
		cset "name='HPR Mixer RDACR Switch' 1"
	]

	DisableSequence [
		cset "name='HPR Mixer RDACR Switch' 0"
		cset "name='HPL Mixer LDACL Switch' 0"
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 0"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
		PlaybackRate 48000
		PlaybackMixer "hw:${CardId}"
		PlaybackMixerElem "Digital Output"
		JackControl "Headphone Jack"
	}
}

SectionDevice."Speaker" {
	Comment "TFA9890 Speaker"

	ConflictingDevice [
		"Headphones"
	]

	EnableSequence [
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='SEC_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='Amp Input' Left"
	]

	DisableSequence [
		cset "name='SEC_MI2S_RX Audio Mixer MultiMedia1' 0"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
		PlaybackRate 48000
	}
}
